### ISSUE TITLE
People page item number is off for some creators

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#10]
It's great that on the People page, the number of items in the database show up under the creator's name. Most of them seem correct. I can't, however, figure out why Wang Qingsong has 8 items under his name. When you go to his [page](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/113), there are only 6 works.

**Comment by zploskey** [comment]
This was the case when they were creator/contributor more than once per work. I've fixed this, will push an update soon.

**Comment by swelland** [comment]
Aha! Thanks!

Sasha Su-Ling Welland
Associate Professor
Gender, Women & Sexuality Studies
University of Washington
Box 354345
Seattle, WA 98195-4345
vm 206.221.4725
fax 206.685.9555
https://gwss.washington.edu/people/sasha-su-ling-welland
