### ISSUE TITLE
Some creators are now missing from the People page

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#11]
It's great that the People page is now ordered alphabetically by last name. I noticed, however, that a few people who used to show up on the People page no longer do, such as Xie Jin, Yin Xiuzhen, and myself. Do you know what's going on?

**Comment by zploskey** [comment]
Turns out the ultimate cause of this bug was in Omeka itself. See the last commit message.

**Comment by zploskey** [comment]
Reported in omeka/Omeka#819.
