### ISSUE TITLE
Short paragraph for below image carousel on homepage

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#12]
As we discussed yesterday, there will be just one consolidated block of text for the homepage. Please use this paragraph (only the title of the book should be in italics): 

_Experimental Beijing: Gender and Globalization in Chinese Contemporary Art_ (Duke University Press, 2018) is a book by Sasha Su-Ling Welland. Grounded in ethnographic and visual interpretation, it explores Chinese contemporary art at the turn of the millennium as a zone of cultural encounter — between ideas of masculinity and femininity, public and private, rural and urban, China and the world. A feminist lens provides insight into the interlocking power dynamics involved in the shifting role of art during an era of experimentation. This digital companion, designed to complement and visually deepen the experience of reading the book, features expanded multimedia materials and provides readers with a nonlinear way to explore the image worlds it proposes.

**Comment by zploskey** [comment]
Thanks, this text is now in Transifex with this change zploskey/plugin-ExperimentalBeijing@377f426 and deployed to the site.
