### ISSUE TITLE
About "exhibit" navigation

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#13]
I've set up the About "exhibit" in English and Chinese. Mirroring seems to be working. I'm not sure how to set up it up in navigation. I added links for both exhibits/show/about and exhibits/show/about-zh_cn, but then both English and Chinese show up in the menu navigation in both English and Chinese mode.

**Comment by zploskey** [comment]
I'll need to filter out exhibit links by their MultilanguageContentLanguage. I'll handle that in the plugin, so you can leave it as is.

**Comment by zploskey** [comment]
User-set links aren't filterable from where I was trying to do it. Will try another approach.

**Comment by zploskey** [comment]
This required creating a new filter in the base project in e63a499.
