### ISSUE TITLE
New item type metadata fields for print version and page number?

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#14]
I've been proofing the items in the image gallery for Chapter 1: Xianfeng Beijing. We had previously discussed including book reference information (plate/figure, chapter, page numbers) in the description field, as in this [item](http://depts.washington.edu/expbj/ExperimentalBeijing/exhibits/show/xianfeng-beijing/item/694). I'm now wondering if that's the best way to handle this issue.

In Siyi's design for the chapter image gallery, there is a hover box that will appear over item thumbnails with the following info: Title (date); page number. Should we add an Item Type metadata field (for still image, moving image, and series) for page number so that the code can pull it up to appear in this hover box? We could perhaps use all of the following fields: Figure Number, Plate Number, Chapter, Page. This information could then appear (if filled out) below Description, maybe in a single line labeled Book Reference. 

Her design also includes a bookmark icon on item thumbnails of images that appear in the print version. Should we add an Item Type metadata field (yes/no) for whether the item will be in the print book?

I can try to add these new metadata fields, but I wanted to run things by you first.

**Comment by zploskey** [comment]
Adding the number fields you mentioned seems like a good way to go. We can determine if it is in the book from those fields, so no need to add a yes/no field.

**Comment by swelland** [comment]
I've added the fields plate, figure, chapter, and page to the Still Image and chapter and page to Moving Image item type.

I don't have the final page proofs yet, so I can only fill out plate or figure and chapter. 

Still image (plate) example with filled fields: Item #696
Still image (figure) example with filled fields. Item: #679

In the About block, the following should go after Description:
Book Reference: plate # or figure # (which ever is filled out), chapter #, page # 

If there is a plate or figure # listed, we know it is in the print version and should have the bookmark icon on the thumbnail in the Chapter image gallery.
