### ISSUE TITLE
Get rid of Description repetition

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#15]
We talked about this at one meeting but then I think left it hanging.

We noticed that Description is used twice. Once for the core block of metadata that first appears under an image, and then within that block. 

Let's use About (关于) for the overall block of metadata and then keep Description as the DC element field within the block.

**Comment by zploskey** [comment]
Fixed in zploskey/omeka-theme-experimental-beijing@d0c2fa15.
