### ISSUE TITLE
Homepage-Admin Images

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#16]
I've added twelve new images to the Admin Images folder for the homepage. None of these have transparent or white borders. Some of them are dups from what had previously been uploaded. Once we know everything is working, I can delete these old ones.

It appears that the items are displaying in the carousel according to the item number included in the items/show/# link. If possible, I would like them to appear in the following order: 892; 733; 942; 732; 689; 697; 696; 943; 679; 944; 714; 945.

The carousel currently seems limited to 10 images. Can we bump it up to 12?

**Comment by zploskey** [comment]
Items 944 and 945 don't exist and I'm not sure what AdminImages you're referring to for them.

I pick which items to use by their AdminImage ID, not their item ID. I think I translated that list order into AdminImage IDs, but it might be better to have you double-check.

The list I have is: 6,7,15,8,14,17,9,10,11, <whatever 944 is>,13,<whatever 945 is>

I'll also up the limit to 20. It's arbitrary, the 10 limit is just the default for ShortcodeCarousel.

**Comment by zploskey** [comment]
I'm guessing they are supposed to be either 12 or 16, as those are the two that don't have items/show links set of the new ones you uploaded. Sticking those in for now.

**Comment by zploskey** [comment]
Ordering these by a custom order may not be so simple as I was thinking. If you provide a list of ids they will be ordered by id by default, and you can provide a custom order but it must be based on one of the record's fields. That's just how ShortcodeCarousel works, I guess. In other words, the order is the order in which they appear in the AdminImages page.

We could probably abuse this by applying sorting on one of the AdminImage fields we don't use like title. I'll try messing with that. For now at least it's the images you wanted. I deleted all the images with white padding. I have not adjusted for varying widths and heights yet.

**Comment by swelland** [comment]
Yes, you were right about 12 and 16. Sorry about that. I haven't added them as items yet, but they are next in the queue for entry so will be Item IDs 944 and 945. Thanks for deleting the ones with white padding.

If custom order is too time consuming, don't worry. I can always delete and re-add these in the desired order, now that I know how the shortcode carousel works. 

In case it might work, the desired order based on AdminImages ID is: 6,7,15,8,14,17,9,10,11,12,13,16.
