### ISSUE TITLE
Is Part Of series

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#17]
I'm trying to add series. I followed the method that I used for [Portable Cities](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/937): (making a new item, add it to the Collection: Series) that uses the name given in the Is Part Of metadata for multiple image items. However, when I did this for Urban Fiction, the associated works (this [one](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/695) and this [one](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/696)) don't show up on the series [page](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/941).

Any ideas of what I've done wrong? Thanks!

**Comment by zploskey** [comment]
It looks like Urban Fiction (the series) has a space at the end of it. Remove that and it should work.

**Comment by swelland** [comment]
I tried that, but no luck yet.

**Comment by zploskey** [comment]
We need to be sure that every one of these series items has its Item Type set to "Series". When editing the series item, click on "Item Type Metadata" at the top, and set the Item Type to "Series". What collection it is in does not matter for fetching related works, but it does make them show up in the Series collection under collections/browse.

**Comment by zploskey** [comment]
I saw that you were trying to add multiple role of creator fields on Urban Fiction. If you want to do that that and also have it be Item Type series, you'll need to add role of creator to the series item type.

**Comment by swelland** [comment]
Oh, got it on both counts!
