### ISSUE TITLE
Language mirroring does not work within chapter exhibit image gallery item pages

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#20]
If you navigate to an individual image item page from within a chapter exhibit, Omeka displays the item using a different URL than if you navigate to an item independently.

URL from within exhibit: http://depts.washington.edu/expbj/ExperimentalBeijing/exhibits/show/xianfeng-beijing/item/939

Individual item page: http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/939

If you click on the Chinese language switching button in the first URL (but not the second), it leads to an Omeka error message.

**Comment by zploskey** [comment]
Interesting, I did not realize ExhibitBuilder routes items links through itself. That will screw up the language switch url override code I wrote. Should be a straight-forward fix.

**Comment by zploskey** [comment]
Actually you are getting this error because the corresponding Chinese language exhibit does not have the same item in it. Try adding the same item to the Chinese image gallery and see if you still run into this problem.

**Comment by zploskey** [comment]
Let me know if this is still a problem once the same items have been added. It looks to link to the right place, it just doesn't currently have that image in the Chinese version of the exhibit.
