### ISSUE TITLE
People: show About info next to image

### ISSUE THREAD

**Issue by zploskey** [zploskey/ExperimentalBeijing#27]

**Comment by zploskey** [comment]
While I'm working on this, this block of info displayed here looks like this in the spec:

```
Last Name:   Chen
First Name:  Lingyang
Gender:      Female
Culture:     Chinese
Birth Date:  1975
```

Most people don't seem to have First Name and Last Name filled out, so a name isn't being displayed at all. I was thinking maybe we just make the name part

```
Name: Chen Lingyang
```

where we just call the Title field "Name" on People pages and display the text for the Title there. This slightly reduces the vertical space taken up and requires less fiddling with adding that metadata in the admin.

**Comment by zploskey** [comment]
Although actually the spec has the Title field displayed above the photo, which is inconsistent with how other Item pages display. Is this still what we're looking for?

![image](https://user-images.githubusercontent.com/542191/38958745-01376bbc-4313-11e8-9681-f16f30a228dd.png)

**Comment by zploskey** [comment]
It should look pretty close to that design now. Let me know if there's anything we need to revisit in the design.

**Comment by swelland** [comment]
Hi Zach,

On the people page, I agree with you that it’s probably better to be consistent with the other item pages and remove the title field from above the photo. I think, however, that it’s best to keep the five categories Siyi used to the right of the image: last name, first name, gender, culture, birth date, especially given the confusion often associated with Chinese first and last name order. 

Sasha

**Comment by zploskey** [comment]
Currently the complete title field is being displayed above everything else. I actually feel like having the title (their full name without labels for first and last) displayed somewhere is good. Initially I thought that the title was not displayed, which prompted me to file this issue. I can remove it if that is what you want, but I feel like it does look OK. First and Last Name fields will only show up if they are added for each person item, and each will need to have the translation set as well.

**Comment by swelland** [comment]
Yes, I agree that it looks fine to have the title displayed. First and Last Name fields as filled out are not yet showing. For example, I just checked [Pan Yuliang](http://experimentalbeijing.com/items/show/104) in Omeka. First and Last Name fields are filled out (with the translation set) but they don't appear yet on her person/item page to the right of her image.

**Comment by zploskey** [comment]
These were set to hidden in the Hide Elements plugin, since there was a time where we only used these on the initial import and wanted them hidden. I unhid them (under Plugins -> Configure  on Hide Elements -> unchecking all boxes next to "First Name" and "Last Name") and they now show up.
