### ISSUE TITLE
Exhibit Block (File w/ Text layout): Image file should not have an automatic caption below

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#39]
See for example: [About the Book](http://experimentalbeijing.com/exhibits/show/about/book). 

There should not be an automatic clickable item title below the image file included in the exhibit block (with File w/ Text layout) unless text has been entered in the "Provide a caption" field that appears when adding or editing an item in the exhibit block.

**Comment by zploskey** [comment]
This must be default behavior. I'll look into it.

**Comment by swelland** [comment]
Thanks. It’s weird because it wasn’t there as default when I first added the images yesterday but showed up this morning.

**Comment by zploskey** [comment]
Oh! Apparently images added to the exhibit not in the gallery are also in the class "exhibit-item", the filter I made to add markup to the gallery for showing the title, date and page number on hover are showing up here but without the CSS to overlay them over the image. I can make them hidden by default and only show them in the gallery and that will get rid of it. Unless you want to show the same information on hover here?

**Comment by zploskey** [comment]
I've hidden the overlay and bookmark elements by default unless they're in a gallery. This gets rid of this extra text below the cover image. I deployed the change to the site. The old CSS stylesheet may still be cached so don't be alarmed if you don't see the change right away. If you reload this file first then you should be able to see the change immediately: http://experimentalbeijing.com/themes/experimental-beijing/css/style.css?v=2.6
