### ISSUE TITLE
Chapter Image Gallery navigation

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#40]
Once a user has opened a chapter image gallery (e.g. [Chapter 1](http://experimentalbeijing.com/exhibits/show/xianfeng-beijing/image-gallery)) and clicked on an image to open it (e.g. http://experimentalbeijing.com/exhibits/show/xianfeng-beijing/item/939), is there a way to provide navigation to allow the reader to move backwards or forwards from image to image within the gallery, while reading along in the book, or to return back out to the image gallery with thumbnails?

**Comment by zploskey** [comment]
It looks like we can probably accomplish this in a plugin using these previous/next filters: https://github.com/omeka/Omeka/commit/12946d6bcb629845d234644a55672b68ecf9c252
