### ISSUE TITLE
Chinese Menu: Credits

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#41]
I decided that the best way to display the credits was as an exhibit rather than simple page. I created English and Chinese exhibits. Everything seems to be working, except that in the drop down menu, the fifth item down says 关于作者 (about the author) instead of what it should: 致谢名单 (credits), although when you click it, you go to the correct page: http://experimentalbeijing.com/exhibits/show/credits-zh_cn/website-design. I can't figure out why it's displaying the wrong title in the menu.

**Comment by zploskey** [comment]
I'm not entirely sure where this translation is coming from yet, but the translation function returns "关于作者" when given "Credits". We should be able to override it in our translations in the plugin.

**Comment by zploskey** [comment]
That phrase "关于作者" is the default translation defined in Omeka ExhibitBuilder for "Credits", which is part of the Exhibit metadata. Do you think this is something that should maybe be changed in Omeka's ExhibitBuilder? We can set our own translation regardless of whether it's a change they want to make.

**Comment by swelland** [comment]
Zach, Thanks for figuring this out! The Exhibit Builder translation (关于作者), which is more like “about the author/authors,” works if there were just one or two people who “authored” the project. The translation I chose for Credits (致谢名单) is more like “credits list” or “acknowledgments.” I’m in the middle of the teaching intensive part of my week again but will respond to your other message about setting up a meeting time tomorrow. Sasha
