### ISSUE TITLE
Creator with two roles

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#7]
Thanks for fixing the display for pieces with two creators. I've noticed one problem this creates. There are a few pieces in which the creator has two roles, such as: http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/687

This is fine in the description block, where the name shows up twice with the different roles following in parentheses, but it looks weird in the caption at top, to the left of the image.

**Comment by zploskey** [comment]
Forcing the list of creators to only have unique entries is probably the easiest way to fix this.
