### ISSUE TITLE
Dublin Core Language Field needs "translate to"

### ISSUE THREAD

**Issue by swelland** [zploskey/ExperimentalBeijing#9]
For the film clips that are entered into the database, I will fill out the DC field "language." This field does not currently have a "Translate to: zh_CN option." See this [page](http://depts.washington.edu/expbj/ExperimentalBeijing/items/show/726?lang=zh_CN#more-info-section) as an example of how the field remains untranslated. Please add this option.

**Comment by zploskey** [comment]
If you just want to enable the Translate to: zh_CN you can go to the admin, click on Plugins at the top, go down to Multilanguage and click "Configure". You should be able to check the Language field to enable it.

However, if there are only going to be a few languages we could use a controlled vocabulary and translate it from transifex.

**Comment by zploskey** [comment]
I went ahead and enabled translation through the Multilanguage plugin for Language for now.

**Comment by swelland** [comment]
Thanks Zach for this reminder! And then thanks for going ahead and taking care of it. Right now, the only languages I can think of are English and Chinese/Mandarin. Maybe a controlled vocabulary would make sense. Sasha

Sasha Su-Ling Welland
Associate Professor
Gender, Women & Sexuality Studies
University of Washington
Box 354345
Seattle, WA 98195-4345
vm 206.221.4725
fax 206.685.9555
https://gwss.washington.edu/people/sasha-su-ling-welland

**Comment by zploskey** [comment]
I've added Language to the list of elements to translate from the translation files. I put in "Chinese", "English" and "Mandarin" into the Simple Vocab plugin for Language so far. Let me know if you add more, as we'll also need to add those strings to the translation files in Transifex.
